### PR TITLE
Removed GIL lock while compress and decompress

### PR DESCRIPTION
**Pull request by sudeep9**

### CODE REVIEW

**Comment by makmanalp** [comment]
The dask / fastparquet users among us would really appreciate this!

**Comment by andrix** [comment]
@makmanalp it will happen, @martindurant has become a new collaborator of the project and I'm sure he'll review it and merge it.

**Comment by martindurant** [comment]
I can confirm that before this change, found compressions in parallel threads took four times the time, but not after this change. It would be nice to have a test for this, but I'd be OK to forgo it if there are no ideas of how.

**Comment by mrocklin** [comment]
Well, we could also do a timing test.  This could be somewhat conservative.  If we're on a machine with more than a couple of CPUs we should see at least a 20% speedup, or something like that.

**Comment by pitrou** [comment]
Or we trust that we won't remove the `Py_BEGIN_ALLOW_THREADS` by mistake, and we don't bother testing for it. CPython typically doesn't test for such things.
(however, a test that multi-thread compression or decompression produces the right results might be desirable)

**Comment by martindurant** [comment]
OK, I say merge now.

**Comment by makmanalp** [comment]
Thank you!

**Pull request merged**
