### PR TITLE
Github Actions + Manylinux Wheels

### PR DESCRIPTION
**Pull request by ynouri**
(This PR was previously open as #100, but after I squashed my commits it seems like I had no choice but open a new one)

After a little bit more work:
* I was able to build a wheel for CPython 2.7
* I added a Github workflow for PyPy 2 and 3.
* Somehow the PyPy 2 test failing in the Travis builds runs fine in Github Actions... not sure if it's worth investigating.
* This means that in the current state, the Github workflow included in this PR covers everything previously done in Travis, and does more (build and publish CPython Linux wheels)
* I uncommented the Twine upload section, which means that if the PyPI secrets are correctly defined, the wheels should be published to PyPI after this PR is merged to `andrix/python-snappy:master`.
* Do we want to bump the version in `setup.py` from `0.5.4` to `0.5.5` or `0.6.0`? In case there is a problem with the wheels, consumers would still have the option to pin down `python-snappy==0.5.4`.

### CODE REVIEW

**Comment by ynouri** [comment]
Copying remarks from the previous PR:
* The Github workflow I added seems to run fine in my own fork, however it does not seem to run here. I suspect somebody with admin access to `andrix/python-snappy` would need to enable Github actions.
* Regarding the PyPI Twine upload: somebody with admin access would need to make sure the `PYPI_USERNAME` and `PYPI_PASSWORD` secrets are defined in `andrix/python-snappy`

**Comment by martindurant** [comment]
Wouldn't it make sense to separate out CI tests, that run on PRs (and pushes to master), and the build/upload, which only happens on a new release/tag?

**Comment by martindurant** [comment]
Aside from that, things look alright to my uneducated eyes, but I'd love a review by someone more experienced in gh-actions/pip.

Thanks for the effort here, @ynouri !

**Comment by ynouri** [comment]
> Wouldn't it make sense to separate out CI tests, that run on PRs (and pushes to master), and the build/upload, which only happens on a new release/tag?

I changed the condition which enables/disables the PyPI upload, it is now: `if: startsWith(github.ref, 'refs/tags/0.')`. I tested it by pushing a tag on my repo and it works (also the upload doesn't happen anymore on master branch).

Regarding the build, I thought it was good practice to build the wheel and run the tests on the installed wheel (which is actually built in a different container with older libraries for manylinux compatibility) rather than run the tests directly on the installed source. This guarantees that what we distribute is what we tested.

> Aside from that, things look alright to my uneducated eyes, but I'd love a review by someone more experienced in gh-actions/pip.
> 
> Thanks for the effort here, @ynouri !

Sure, appreciate the feedback and guidance! Anybody we could ping for a final review? @andrix maybe?

**Comment by martindurant** [comment]
I think this will have to be @andrix yes - I don't seem to have the ability to add pypi secrets to this repo (PYPI_USERNAME, PYPI_PASSWORD). 
@ynouri , would the build/upload happen when a new tag is pushed to master, or does it require a manual "release" via the github interface?

**Comment by ynouri** [comment]
The Github actions build/upload should be triggered as soon as a git tag starting with "0." is pushed to the repository (I tested this on my fork).

It is not tied to Github's releases, even though we could consider adding later this action that automatically create a release after the build.
https://github.com/actions/create-release

**Comment by martindurant** [comment]
If the workflow is to build and potentially upload the manylinux binary, I'd rather it also packaged the sdist, since that out to always be uploaded to pypi at the same time. Aside from that, I think we should go ahead with this to get working CI again. The next release would be 0.6.0, but as I said above, only @andrix can add secrets to this repo, so that's a blocker.

**Comment by andrix** [comment]
Hello @martindurant @ynouri - I'm sorry for the radio silence here. I would be happy to help. What's needed from my part? It seems I need to add a secret to the repo. Would you mind letting me know, and I'll do it.

Sorry for the lack of answers, I'm driving over some very busy times of my life with my kids, covid and work.

**Comment by ynouri** [comment]
Hello @andrix , thanks for the help! I would have suggested to give @martindurant access to the Github repository settings (since he's already a maintainer on PyPI), but according to Github documentation on [user owned repositories](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository), it's not possible. Looks like this feature is only available in [organization owned repositories](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization), which is probably too much hassle...

So probably easier to just have you set up the secret. To do so I believe you need to roughly follow those steps:
1. Browse to https://pypi.org and log in
2. Go to python-snappy project settings: https://pypi.org/manage/project/python-snappy/settings/
3. In the API tokens section, click on "Create a token for python-snappy" and follow instructions. The token name in PyPI does not really matter, maybe just name it "Github"
4. Now go to Github, open andrix/python-snappy repository settings: https://github.com/andrix/python-snappy/settings/secrets/actions
5. Click "New repository secret", name it `PYPI_PASSWORD`, and paste the token from PyPI.org
6. Again, click "New repository secret", name it `PYPI_USERNAME`, and use the value `__token__`

I think that should be it.

**Comment by ynouri** [comment]
Note: I tested the upload on test.pypi.org, and it seems to work.

image

**Comment by ynouri** [comment]
@martindurant - regarding the sdist, I completely forgot about it. Let me add it to the workflow and upload.

**Comment by ynouri** [comment]
Just added the sdist. Seems to upload fine to test.pypi.org. Feel free to take a look to see if everything looks in place:
https://test.pypi.org/project/python-snappy/0.6.3/#files

(Note: ignore the 0.6.3 version, I just used this for my tests)

**Comment by andrix** [comment]
@ynouri - Amazing. I have added the `PYPI_*` secrets as Repository secrets, and setup the token in PyPI as described. Thank you for the clear steps.

Also, I made @martindurant an Owner on the PYPI `python-snappy` project that will give you the right permissions to do changes on the settings if needed.
@ynouri - can you test and let me know if it works?

**Comment by martindurant** [comment]
> I'm sorry for the radio silence here

We are grateful for your continued involvement!

**Comment by ynouri** [comment]
@andrix @martindurant to test the official PyPI upload we would need to:
1. Merge this PR
2. Confirm build on `andrix:master` is green
3. Update new version in `setup.py` as desired (I can add the bump in this PR but probably better handled separately?), e.g. `0.6.0`. Not sure if there are other steps in the release process (e.g. updating a change log?)
4. Create tag for 0.6.0: `git tag 0.6.0`
5. Push tag to repo: `git push origin 0.6.0`
6. A new Github Actions build should be automatically triggered on the pushed tag event
7. Confirm the PyPI upload step in the `wheel` and `sdist` workflows passed
8. Confirm the artifacts are available under new version on PyPI.org

I believe most steps above would require merge rights on the repo - let me know if I can help.

**Comment by andrix** [comment]
@martindurant - thank you so much. I'm happy for all your help, and I hope to have more time on 2021 for open source & coding (getting back to my roots).

@ynouri @martindurant - I reviewed the PR and it seems fine to me, so I think we can merge it and follow the steps suggested by Yacine. Will you take care, or you prefer I do it?

**Comment by martindurant** [comment]
Merged!

**Comment by andrix** [comment]
@martindurant @ynouri - I have created the version 0.6.0 and pushed to master and 0.6.0 branch. PyPi has the released for 0.6.0, and it should be correct.

Would you mind confirm that in your side everything works as expected?

**Comment by martindurant** [comment]
On OSX, pip installed v0.6.0 from source, with compilation - but it worked.

**Comment by andrix** [comment]
Thanks @martindurant - I can confirm the same on MacOS BigSur and Py 3.8.2. 

@ynouri - if you have access to other env, would you mind confirm it as well?

**Comment by ynouri** [comment]
Installation and build worked for me as well on MacOS and Ubuntu.

However I tried to re-run my original end-to-end use case (ie reading and writing parquet files) with Pandas but I'm a bit puzzled by the behavior. It looks like the parquet engine `pyarrow` can use snappy compression without `python-snappy` installed. I'm under the impression that `pyarrow` has some direct snappy bindings (maybe at their C++ library level). Did I dream that `pyarrow` ever had a dependency on `python-snappy`?  👀

Snippet I've been using for E2E test: https://gist.github.com/ynouri/5a63b521c6b4b751cdc1e7b3e384622d

**Comment by martindurant** [comment]
> Installation and build worked for me as well on MacOS and Ubuntu.

You misread my comment: installation for me resorted to compilation, which should *not* happen when the wheels are available. So what happened?

**Comment by ynouri** [comment]
> You misread my comment: installation for me resorted to compilation, which should *not* happen when the wheels are available. So what happened?

The PR added build for Linux x64 wheels, Python 3.5 -> 3.9.

MacOS and Windows, as well as other architectures than x64 (e.g. x86 or ARM) were not included.

The zstd Python bindings provide a good example of how to build for those:
https://github.com/indygreg/python-zstandard/blob/main/.github/workflows/wheel.yml

**Comment by martindurant** [comment]
Right, "manylinux". I must have momentarily thought that mac was linux :|

**Pull request merged**
