### PR TITLE
Github Actions + Manylinux Wheels

### PR DESCRIPTION
**Pull request by ynouri**

### CODE REVIEW

**Comment by ynouri** [comment]
@martindurant some cleanup and a git squash are probably needed - but wanted to put this out to get some early feedback.

**Comment by martindurant** [comment]
Any idea why travis' pypy would fail on the one test?

Is this workflow/action running somewhere on a. branch?

**Comment by martindurant** [comment]
Oh, I see you had an image on the linked issue, sorry.

Thanks for working on this. I don't think I have the knowledge to comment, perhaps someone can be pinged to help review?

**Comment by ynouri** [comment]
Hi @martindurant,

Thanks for looking at this!

A few notes:
* The Github workflow I added seems to run fine in my own fork, however it does not seem to run here. I suspect somebody with admin access to `andrix/python-snappy` would need to enable Github actions.
* The Travis failure on PyPy 2.7 doesn't seem related to my PR. As far as I can tell master branch has failed this test for a while - see https://travis-ci.org/github/andrix/python-snappy/jobs/730362937. Fixing this issue is probably out of scope for this PR.
* I will work on adding PyPy support to the new Github actions workflow though. This means the test coverage should be equivalent to what is done today in Travis.
* I'm curious whether it would make sense to remove tests for CPython 2.7 and PyPy 2.7? Python 2.7 reached EOL almost a year ago already. This would magically make the PyPy 2.7 failure go away...
* Regarding the PyPI Twine upload: I haven't tried it on my side but it is configured in the Github workflow. Somebody with admin access would need to make sure the `PYPI_USERNAME` and `PYPI_PASSWORD` secrets are defined in  `andrix/python-snappy`

**Comment by ynouri** [comment]
Let me work on this and re-open later.

**Comment by ynouri** [comment]
@martindurant I had to re-open the PR under #101

**Pull request closed without merging**
