### PR TITLE
Fix Python 3.8+ DeprecationWarning: PY_SSIZE_T_CLEAN will be required for # formats

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Fixes https://github.com/andrix/python-snappy/issues/97.

### CODE REVIEW

**Comment by martindurant** [comment]
Sounds reasonable to me - but I am no C++ coder. If there are no objections, I can merge in 24hr (please ping me if I forget!).

**Comment by ShaneHarvey** [comment]
It seems the Travis CI job is not displayed here on the PR but it did actually run (the PyPy failure already exists on master): https://travis-ci.org/github/andrix/python-snappy/builds/726109324

I've faced this issue before (travis not showing up for PRs) and fixed it by:
- Go to your account at https://travis-ci.org/account/repositories
- Press "sync account". If you get an error syncing then log out of travis and log back in.
- Toggle the  andrix/python-snappy repro off, then toggle it back on.
- Github should now display the travis job on PRs again.

**Comment by andrix** [comment]
@ShaneHarvey I followed the steps on TravisCI and I'm getting and error when building, a failure when testing. I will need to review it. Allow me to do that, and merge this and other PR I have pending.

**Comment by ShaneHarvey** [comment]
Thanks, the Travis job is now showing up again, looks like it worked! 

> I'm getting and error when building, a failure when testing.

Are you referring to the PyPy failure? If so that failure is also happening on master so it appears to be an unrelated bug:
```
ERROR: test_decompression (test_snappy.SnappyStreaming)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/andrix/python-snappy/test_snappy.py", line 229, in test_decompression
    decompressor.decompress(compressed_data[split1:split2]) +
  File "/home/travis/build/andrix/python-snappy/snappy/snappy.py", line 235, in decompress
    raise UncompressError("stream missing snappy identifier")
UncompressError: stream missing snappy identifier
```

**Comment by andrix** [comment]
@ShaneHarvey yes, correct. Sorry it's taking longer, I was trying to debug what was going on with the tests, and I found also a small bug introduced when supporting  pypy+cffi. 
I will hope to work this week on this, but it's a side project for me now and little time due to Covid-19 and kids at home.

**Comment by ShaneHarvey** [comment]
Any chance this can be merged? As described above, the PyPy test failure is unrelated to the changes in this PR. This PR will also unblock https://github.com/andrix/python-snappy/issues/93

**Pull request merged**
