### PR TITLE
Fix #76: support new buffer API

### LINKED ISSUE #76: Add memoryview support in _crc32c
#72 allows users to compress memoryviews via `snappy.compress` interface.
However, `StreamCompressor.add_chunk` raises TypeError when generating crc:

```
env36/lib/python3.6/site-packages/snappy/snappy.py:139: in add_chunk
    crc = _masked_crc32c(chunk)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

data = <memory at 0x7fb4e4cad648>

    def _masked_crc32c(data):
        # see the framing format specification
>       crc = _crc32c(data)
E       TypeError: argument 1 must be read-only bytes-like object, not memoryview
```

Looks like `snappy__crc32c` should be refactored to also support the buffer protocol.

### PR DESCRIPTION
**Pull request by khvn26**

### CODE REVIEW

**Comment by martindurant** [comment]
Fixes #76 ?

**Comment by martindurant** [comment]
Looks good.
Since I am not an expert here, we can leave this up a day for anyone else interested to comment.

**Comment by khvn26** [comment]
Thanks!

**Comment by khvn26** [comment]
Sorry to bump this, but is this going to be released?

**Comment by martindurant** [comment]
Pushed version 0.5.4 to pypi, conda coming soon.

**Pull request merged**
