### PR TITLE
Update dependencies in README

### PR DESCRIPTION
**Pull request by gliptak**
#111

### CODE REVIEW

**Comment by martindurant** [comment]
+1

@gliptak , would you like to be a maintainer on this package?

**Comment by gliptak** [comment]
@martindurant I'm open to assist moving some items along (the package had no significant activity in previous period)

**Comment by martindurant** [comment]
Embarrassingly, I do not seem to be an admin myself, only a collaborator, because the repo is in @andrix 's personal space. I do have access to pypi and the feedstock, so I can make the release when ready. 

@andrix , would you be willing to grant access or move this repo to an org I can manage (e.g., intake or fsspec) ?

**Comment by andrix** [comment]
@andrix Yeah, of course @martindurant - happy to help. We can move it to an agreed org, or create a new one like "python-snappy". What's your preference?

**Comment by martindurant** [comment]
I think intake/ makes sense. @andrix , I can make you temporary admin in that org, so you can execute the move. Is that fine with you?

**Comment by martindurant** [comment]
@andrix , I have invited you to intake/ , please transfer this repo when you have a moment.

**Comment by martindurant** [comment]
ping @andrix , I hope you received the invite from intake.

**Comment by andrix** [comment]
@martindurant –sorry Martin! It's been a busy week here, I just transferred the repo to the Intake organization. It's sad after all this time, but I know you're taking care of it with care and love :). I would still ask if you can leave me as shared owner on the intake org for that repo if it's not too much to ask.

**Comment by martindurant** [comment]
> I would still ask if you can leave me as shared owner on the intake org for that repo if it's not too much to ask.

of course.

**Pull request merged**
