### PR TITLE
Bump joerick/cibuildwheel to v1.12.0 in GHA

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/andrix/python-snappy/issues/113

### CODE REVIEW

**Comment by gliptak** [comment]
@martindurant please approve running workflow

**Comment by martindurant** [comment]
Can you please update the selectors in setup.py?

**Comment by gliptak** [comment]
@martindurant I'm not sure what selectors you reference above (I couldn't get a green Python 3.10 build yet)

**Comment by gliptak** [comment]
@martindurant build is green. any updates you would like to see?

**Pull request merged**
