### PR TITLE
Vagrant scripts indicted how to install python-snappy on Ubuntu.

### PR DESCRIPTION
**Pull request by crossz**
README about how to install it on Linux (Ubuntu 16.04 here).

### CODE REVIEW

**Comment by crossz** [comment]
Seems only 'apt install python-snappy' will make it works. No need to compile from scratches.

**Comment by martindurant** [comment]
You think the vagrant path should be updated even though the apt-install works for you?

**Comment by crossz** [comment]
Vagrant is easy to test the installation. Actually, not necessary.
However, yep, apt-install works, but pip fails. The latter is the python way in my flavor. 
So I am still struggling make all of these work through google/snappy compiling and pip-install for python-snappy.

**Comment by crossz** [comment]
This PR includes some unnecessary steps. I should close it.
And do you think it's proper that I provide vagrant stuff as the python-snappy installation test?

**Comment by martindurant** [comment]
Since I am new to being involved in this repo (which was lacking maintenance) , I am not sure. Generally speaking, the wider range we can cover for install options the better, but there is not much effort available. In practice, we have no stats on how people currently install, or which methods have demand but are not met.

Specifically, I am happy to see testing via vagrant if it can be a long-term solution - but clearly it's not something I would know how to contribute to!

**Comment by crossz** [comment]
Ok, then. Let me put my test results into the issue #50.

**Pull request closed without merging**
