### PR TITLE
Add hadoop snappy format support alongside with framing format

### PR DESCRIPTION
**Pull request by aleks-v-k**
See #61

### CODE REVIEW

**Comment by martindurant** [comment]
Thank you for the PR, @aleks-v-k . I won't have the time immediately to look through this, I hope others chime in. Am I right in thinking that the intent is to apply decompress on any data/stream, and detect the framing format in order to call the right method?

**Comment by aleks-v-k** [comment]
> Am I right in thinking that the intent is to apply decompress on any data/stream, and detect the framing format in order to call the right method?

No, the patch doesn't introduce any format detection. The default format is the original framing format implemented in this python-snappy library. The patch just adds an optional support for hadoop snappy format. To use it in (de)compression a user should specify it explicitly:
* `-t hadoop_snappy` option for (de)comressing via `python -m snappy`
* call `snappy.hadoop_stream_compress` or `snappy.hadoop_stream_decompress` inside a python script

**Comment by martindurant** [comment]
OK, I guess that's a safe way to proceed. Is there a way to determine the framing?

**Comment by aleks-v-k** [comment]
I think there it is a way. At least it's implemented in snzip project. Ok, if you will this (format detection) to be implemented, then I will do it till end of this week.

**Comment by aleks-v-k** [comment]
I've implemented format autodetection, please review the last commit in the PR.

**Comment by martindurant** [comment]
Nice tests in `test_formats.py`.
I'll merge this now, thank you for the work.

**Comment by aleks-v-k** [comment]
Thanks!

**Pull request merged**
